#! /bin/sh


# BSPWM Autostart

pgrep -x sxhkd > /dev/null || sxhkd &
$HOME/.config/polybar/launch.sh
picom --experimental-backends &
nitrogen --restore &
xsetroot -cursor_name left_ptr &
lxsession &
setxkbmap -layout us -variant intl &

#BSPWM basic configuration

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         3
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true
bspc config left_padding         6
bspc config right_padding        6


bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off


#BSPWM coloring

bspc config normal_border_color		"#c0caf5"
bspc config active_border_color		"#7aa3f7"
bspc config focused_border_color	"#bb9af7"
bspc config presel_feedback_color	"#ff9e64"
#bspc config urgent_border_color 	"#dd2727"


